### ISSUE TITLE
Game Runs AWFUL When Generating Trees Now

### ISSUE THREAD

**Issue by SuperFanatic** [TannyJungMC/THT-tree_pack#6]
Just updated to the new version (1.19.2, mod version 4.4.6.1) And got the new Tree Pack. On the previous version, I had a little lag when generating trees, but understandable considering the huge trees being generated. Now, When generating even a Halcyon or similar the game runs at 1-frame-per-20-seconds at BEST. Tested with both natural tree generation and with a sapling, same results. I've restarted the game, deleted my configs, still nothing.

Also, side question: Where did the "global_rarity" config option go? I had it set to 1 so the trees were rare but now it's gone? Do I have to set every tree's rarity individually now?

**Comment by TannyJungMC** [comment]
To be honest, I haven't test the 1.19.2 yet 😂 I mostly focus on 1.20.1 now, will try it today to see is it very lag like that.

For the "global_rarity" config, I removed it since I changed tree location system, you need to edit it manually using a datapack now. But maybe not, don't need to do that, thanks for report, I just remembered I can bring it back. Should be new update for this coming soon.

**Comment by TannyJungMC** [comment]
Fixed, it because I set wrong name for world gen armor stand, that make them not disappeared and become huge lag. After you update to the fix version, try manual remove those using command `/kill @e[name=THT-tree_placer_forceload]`

**Comment by SuperFanatic** [comment]
Upon testing, it appears you fixed the problem, but only on natural trees. Ones placed with a sapling still lag everything to heck. Not a problem in survival but makes testing a pain. Global Rarity seems to work fine though.

**Comment by TannyJungMC** [comment]
Just found out there's other one armor stand that have wrong name too, in tree sapling. Already fixed in next update.

**Comment by SuperFanatic** [comment]
Sorry for the late reply. Thank you, the mod seems to work perfect once again.
